feat: move to verify testnet
verify-media/getting-started pull request #1
Opened 2024-04-10 12:52 UTC by anky2k

2024-04-10 14:39 UTC, jadaca0 requested changes

2024-04-10 14:39 UTC, jadaca0 commented on README.md
Might be good to have the link for getting started to go do the guide directly, instead of the landing page

2024-04-10 14:39 UTC, jadaca0 commented on index.js
Would it be better to create one instance of the RPC provider as a const at the top of the file, instead of all the inline instantiations

2024-04-11 10:35 UTC, anky2k commented
@jadaca0 resolved comments

2024-04-11 13:12 UTC, jcbck approved these changes

2024-04-11 14:26 UTC, jadaca0 commented
LGTM

2024-04-11 14:26 UTC, merged